config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'home#index'

  get '/home', to: 'home#private'

  get '/signup', to: 'devise/sessions#new'

  get '/profile', to: 'home#profile'

  get '/aide', to: 'home#aide'

  get '/contact', to: 'home#contact'

  get '/comment-ca-marche', to: 'home#comment-ca-marche'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike_loan.rb
class BikeLoan < ApplicationRecord
end

app/models/bike_rent.rb
class BikeRent < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def private
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/aide.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
      <%= stylesheet_link_tag "aide.css" %>
      <%= javascript_include_tag "aide.js" %>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="aide.css" />
      <title>Comment pouvant-nous aider ?</title>
    </head>

<header>

    <div class="baniere" style="color:white;">

      <h3>Comment pouvant-nous aider ?</h3>

    </div>

</header>

<body>

  <h2>Locataire</h2>
    <button class="accordion">Quels sont les moyens de paiement acceptés ?</button>
      <div class="panel">
        <p>Vous devez payer la location avec une carte bancaire à votre nom. Seuls les paiements faits avec une carte MASTERCARD, VISA et VISA Electron sont acceptés.<br/>Les chèques, espèces, e-cartes bleues, cartes bancaires prépayées, Maestro, Paypal ou American Express ne sont pas acceptés.</p>
      </div>

    <button class="accordion">Quelles sont les conditions pour pouvoir louer sur Baïkee ?</button>
      <div class="panel">
        <p>Pour louer sur , vous devez :

Être en possession d'un permis de conduire valable dans le pays de location . Si vous avez un permis étranger, cliquez pour en savoir plus.
<br>Respecter les conditions d'âge et d'années de permis correspondant à la catégorie de la voiture louée (voir les conditions par catégorie). <br>
Payer la location sur le site avec un moyen de paiement à votre propre nom. Vous devrez ensuite présenter la carte bancaire utilisée au propriétaire au début de la location. En savoir plus sur les moyens de paiements acceptés.
A noter également, vous devez : <br>

Rester dans les pays européens autorisés (voir la liste des pays). <br>
Ne pas utiliser le véhicule pour faire du transport commercial de personnes (seul le covoiturage, avec partage des coûts, est autorisé). <br>
Rester le conducteur principal du véhicule pendant la location : vous ne pouvez pas louer un véhicule pour l’usage d’une autre personne. Toutefois, tant que vous restez le conducteur principal, le propriétaire peut accepter des conducteurs secondaires respectant les conditions de location. <br>
Le respect de ces conditions est indispensable pour que vous soyez couvert par notre assurance au cours de votre location. Le propriétaire vérifiera ces éléments au début de la location, et vous refusera la location en cas de non-respect des conditions. <br>
</p>
      </div>

    <button class="accordion">Où trouver mon justificatif de paiement ?</button>
      <div class="panel">
        <p>Pour télécharger et imprimer facilement vos justificatifs de paiements, vous pouvez vous connecter à votre compte Baïkee depuis un navigateur web (et non depuis l’appli mobile) puis vous rendre dans : Mes locations > Voir les locations terminées > [location concernée] . <br>Au niveau du prix, cliquez sur "Détails" pour accéder à votre reçu.

S'agissant de location entre particuliers, nous ne pouvons pas fournir de facture avec TVA mais ce justificatif a la même valeur légale et peut servir de note de frais.</p>
      </div>


  <h2>Propriétaire</h2>

    <button class="accordion2">Que faire si le locataire a parcouru plus de kilomètres que prévu ou que le niveau d’essence est différent en fin de location ?</button>
      <div class="panel">
        <p>En fin de location vous disposez de 24h pour demander un ajustement du prix si le locataire a parcouru plus de kilomètres que prévu, ou que le niveau d’essence est différent de celui en début de location.</p>
      </div>

    <button class="accordion2">Quand suis-je payé ?</button>
      <div class="panel">
        <p>Vous êtes payé par virement bancaire dans un délai maximum de 3 jours ouvrés suivant la fin de la location. <br>Les virements mettent ensuite en général 1 à 2 jours ouvrés pour arriver sur votre compte bancaire. <br>

Cela signifie donc que vous verrez apparaître l’argent sur votre compte bancaire entre 4 et 5 jours ouvrés suivant la fin de la location.</p>
      </div>

<script type="text/javascript" src="aide.js"></script>
</body>
</html>

app/views/home/comment-ca-marche.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
      <%= stylesheet_link_tag "comment-ca-marche.css" %>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="comment-ca-marche.css" />
      <title>Comment ça marche ?</title>
    </head>

<header>

    <div class="baniere" style="color:white;">

      <h3>Comment ça marche ?</h3>

    </div>

</header>

<body>
    <div class="container">

      <div class="row">
        <div class="column">

          <h2>Locataire</h2>

            <h1>Besoin d'un deux roues, louez sur Baïkee </h1>

              <div class="main">

                  <article>
                      <header>
                          <h2>1. Cherchez un véhicule</h2>
                      </header>
                      <section>
                          <h2>2. Réservez un véhicule</h2>
                      </section>
                      <section>
                          <h2>3. Récupérez un véhicule</h2>
                      </section>
                      <section>
                          <h2>4. Rendez le véhicule en fin de location</h2>
                      </section>
                      <section>
                          <h2>5. Evaluez la location</h2>
                      </section>
                  </article>

                  <p>
                  <a class="button button_asphalt button_big_cta button_xs_block" href="https://www.baïkee.com/louer-un-deux-roues">Louer un deux roues</a>
                  </p>

              </div> <!-- #main -->

            </div>



            <div class="column">
              <h2>Propriétaire</h2>
              <h1>Rentabilisez votre deux roues sur <br>Baïkee</h1>

              <div class="main">

                  <article>
                      <header>
                          <h2>1. Inscrivez votre véhicule</h2>
                      </header>
                      <section>
                          <h2>2. Recevez des demandes de locations</h2>
                      </section>
                      <section>
                          <h2>3. Retrouvez le locataire</h2>
                      </section>
                      <section>
                          <h2>4. Récupérez votre véhicule</h2>
                      </section>
                      <section>
                          <h2>5. Evaluez la location</h2>
                      </section>
                      <section>
                          <h2>6. Recevez vos gains</h2>
                      </section>
                  </article>

              </div> <!-- #main -->

            <p>
              <a class="button button_asphalt button_big_cta button_xs_block" href="https://www.baïkee.com/inscrire-mon-véhicule">Inscrire mon véhicule</a>
            </p>

</body>
</html>

app/views/home/contact.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
      <%= stylesheet_link_tag "contact.css", media: "all", "data-turbolinks-track" => "true" %>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="contact.css" />
      <title>Comment ça marche ?</title>
    </head>

<header>

    <div class="baniere" style="color:white;">

      <h3>Contacter Baïkee</h3>

    </div>

</header>

<body>
  <p>Que vous soyez locataire ou propriétaire vous pouvez nous contacter en complétant le formulaire ci-dessous. <br> Nous transmettrons votre question à l'équipe concernée et vous répondrons rapidement.</p>

  <div class="container">
    <form action="/action_page.php">
      <label for="fname">Prénom</label>
      <input type="text" id="fname" name="firstname" placeholder="Votre prénom..">

      <label for="lname">Nom</label>
      <input type="text" id="lname" name="lastname" placeholder="Votre nom..">

      <label for="subject">Sujet</label>
      <textarea id="subject" name="subject" placeholder="Votre texte.." style="height:200px"></textarea>

      <input type="submit" value="Envoyer">
    </form>
  </div>

</body>

</html>

app/views/home/index.html.erb
<html>

<head>

  <meta charset="utf-8">

  <link rel="stylesheet" type="text/css" href="header.css">
  <%= stylesheet_link_tag "index.css" %>

  <link rel="icon" href="images/logo.png" sizes="16x16">

  <title>baïkee</title>

</head>

<body id="pages_homepage__index">

  <div id="js_site_content" class="site_content">

  <header class="header">

    <div class='container'>

      <nav class="header_container">

        <a>  <%= link_to image_tag("logo.png", alt: "logo", :class => 'header_logo')

        %> </a>



          <ul class="navbar">

            <li class="navbar_item"><a class='navlink' href=""><%= link_to "S'inscrire", new_user_registration_path, class: "navlink" %></a></li>

            <li class="navbar_item push"><a class='navlink' href=""><%= link_to "Se connecter", new_user_session_path, class: "navlink" %></a></li>

            <li class="navbar_item xs dropdown">

              <a class="navlink dropbtn "  href="/help">Des questions ?

</a>

                <ul class="navbar_subnav dropdown-content" >

                        <li class="navbar_item">
                        <a class="navlink navlink--sub" href="/comment-ca-marche"><%= link_to "Comment ça marche", comment_ca_marche_path, class: "navlink" %></a></li>
                        <li class="navbar_item">
                        <a class="navlink navlink--sub" href="/help"><%= link_to "Aide", aide_path, class: "navlink" %></a></li>
                        <li class="navbar_item">
                        <a class="navlink navlink--sub" href="/contact"><%= link_to "Contact", contact_path, class: "navlink" %></a></li>

                    </ul>

                        </li>



            <li class="navbar_item"><a class="navlink" href=""><div class="flag"><img src="http://www.granadaeditions.com/wp-content/uploads/2013/10/Drapeau-francais-e1463496293603.png" style="width: 19px; height: 19px; viewBox:0 0 19 19;"> </div></a></li>





            <li class="navbar__item">

                <a class="navlink " href="/louer-sa-moto">Louer mon deux-roues</a></li>    



          </ul>

      </nav>

    </div>



</header>

<!--search-->

   

<div id="container">

    <h1 class="homepage_title">Louez les motos près de chez vous</h1>

    <h2 class="homepage_subtitle">Moins cher, plus proche, plus pratique</h2>

    <form id="function_search">

      <% content_for :title do %>Instant-search<% end %>



<% content_for :title do %>Backend-search<% end %>



<div class="container">

  <div class="row">

    <div class="col-sm-6 col-sm-offset-3">

      <%= form_for Contact.new, url: '/backend-search', method: 'get' do |f| %>

        <%= text_field :contact, :q, class: "form-control" %>

      <% end %>

    </div>

  </div>

</div>



<% if @hits %>

  <h2>Results</h2>

  <% @hits.each do |hit| %>

    <div class="hit">

      <%= debug hit %>

    </div>

  <% end %>

  <%#= will_paginate @hits %>

  <%#= paginate @hits  %>

<% end %>
          <div class="col-lg-2 col-md-12 col-xs-12 bottom15">
            <button class="search_button"> Search</button>
          </div>

          </div>  

        </div>

      </div>

    </form>

</div>

<!--  3 eme section avec les suggestions-->





  <div class='cars_slideshow'>

      <div class="container">

        <div class="row">

          <div class="col-xs-12 no-outer-gutter-xs">

            <h2 class="homepage_section_title">

              3 millions d'utilisateurs et plus de 150 000 deux-roues de particuliers à louer en France

            </h2>

            <div class="homepage_motos_slideshow owl-carousel">

              <div class="owl-stage-outer">

                <div class=" owl-stage" >

                <%= link_to image_tag("harley_davidson.jpg", alt: "image", :class => 'moto')%> 

                      <%= link_to image_tag("ER6-N.jpg", alt: "image", :class => 'moto')%> 

                <%= link_to image_tag("MT10.jpg", alt: "image", :class => 'moto')%> 

                <%= link_to image_tag("moto1.jpg", alt: "image", :class => 'moto')%> 

            </div>

            </div>

            </div>

          </div>    

        </div>

      </div>

  </div>



<!-- completez vos revenus -->

<div class="homepage_owner_layer">

    <div class="container">

        <h2 class="homepage_section_title">Complétez vos revenus</h2>

           <p>Inscrivez gratuitement votre deux-roues, puis louez-la quand vous voulez.<br>Soyez tranquille : Allianz assure toutes les locations !</p>

           <div class="top30"><a class="button button_asphalt button_big_cta button_xs_block" href="https://www.baïkee.com/louer-sa-moto">Louer ma moto</a></div>

     </div>

</div>



</div>



 <!-- footer -->



<footer class="js_footers" id="footers">

<div class="footer">

<div class="container">

<div class="row">

<div class="col-md-4 col-xs-12 bottom20">

<h3 class="footer_title"><a href="https://www.drivy.com/a-propos-de-la-location-de-voitures-de-particulier-a-particulier">À propos</a></h3>

<p class="justify">Baïkee vous permet de louer un deux roues parmi les milliers qui sont garés près de vous.

Louez moins cher et plus rapidement.<br>

Si vous possédez un deux-roues, mettez le en location pour qu’il paie ses factures tout seul.

Nous sommes là pour que la confiance règne, en assurant les locations et en veillant à leur bon déroulement.

</p>

</div>

<div class="col-md-2 col-sm-3 col-xs-6 bottom20">

<h3 class="footer_title">En savoir plus</h3>

<ul>

<li><a class="" href="/comment-ca-marche" rel="nofollow">Comment ça marche&nbsp;?</a></li>

<li><a class="" href="/help" rel="nofollow">Accueil de l'aide</a></li>

<li><a href="https://www.drivy.com/contact">Contact</a></li>

</ul>

</div>

<div class="col-md-2 col-sm-3 col-xs-6 bottom20">

<h3 class="footer_title">Découvrir</h3>

<ul>

<li><a class="" href="https://www.drivy.com/assurance-location-voiture-particulier" rel="nofollow">Assurance</a></li>

<li><a href="https://www.drivy.com/contrat-location-vehicule-entre-particulier">Contrat de location</a></li>

<li><a href="https://www.drivy.com/professionnels">Professionnels</a></li>

<li><a href="https://www.drivy.com/mobile">Applis mobile</a></li>

<li><a href="https://www.drivy.com/bons-plans-proprietaires">Bons plans</a></li>

<li><a href="https://www.drivy.com/diagnostic">Diagnostic véhicule</a></li>

</ul>

</div>

<div class="clearfix visible-xs-block"></div>

<div class="col-md-2 col-sm-3 col-xs-6 bottom20" itemscope="" itemtype="http://schema.org/Organization">

<link href="https://www.drivy.com/" itemprop="url">

<link href="https://fr.wikipedia.org/wiki/Drivy" itemprop="sameAs">

<link href="https://plus.google.com/108530477570400575729" itemprop="sameAs">

<h3 class="footer_title">Nous suivre</h3>

<ul>

<li><a itemprop="sameAs" target="blank" href="https://www.facebook.com/Ba%C3%AFkee-338485653287265/?modal=admin_todo_tour">Facebook</a></li>

<li><a itemprop="sameAs" target="blank" href="https://twitter.com/ReelBaikee">Twitter</a></li>

<li><a itemprop="sameAs" target="blank" href="https://www.instagram.com/drivyfr/">Instagram</a></li>



</ul>

</div>

<div class="col-md-2 col-sm-3 col-xs-6 bottom20">

  <h3 class="footer_title">Partenaires</h3>

  <a href="https://www.allianz.fr"><%= link_to image_tag("Allianz.png", alt: "aalianz", :class => 'logofooter')%> </a>



  <div class="top15">

    <a href="https://http://www.thehackingproject.org"> <%= link_to image_tag("thp.png", alt: "thp", :class => 'logofooter')%> </a>   



  </div>

</div>

</div>


<div class="footer_corporate">

<div class="container"> 




<span class="copyright">© Baïkee 2017-2018 </span>



</div>

</div>


</footer>

  <script href="script.js"></script>

</body>

</html>

app/views/home/private.html.erb
<h1>Home#private</h1>
<p>Find me in app/views/home/private.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Location de deux-roues entre particuliers - Drivy</title>
    <%= csrf_meta_tags %>
  </head>

  <body>

  	<p class="notice"><%= notice %></p>
  	<p class="alert"><%= alert %></p>


    <%= yield %>
  </body>
</html>